import { strict as assert } from 'assert';

import {
  ZEPHYR_DIRNAME,
  ZEPHYR_APP_FILENAME,
  ZEPHYR_WORKBENCH_SETTING_SECTION_KEY,
  ZEPHYR_WORKBENCH_PATH_TO_ENV_SCRIPT_SETTING_KEY,
  ZEPHYR_WORKBENCH_VENV_ACTIVATE_PATH_SETTING_KEY,
  ZEPHYR_WORKBENCH_VENV_PATH_SETTING_KEY,
  ZEPHYR_WORKBENCH_LIST_SDKS_SETTING_KEY,
  ZEPHYR_WORKBENCH_LIST_IARS_SETTING_KEY,
  ZEPHYR_WORKBENCH_OPENOCD_SEARCH_DIR_SETTING_KEY,
  ZEPHYR_WORKBENCH_OPENOCD_EXECPATH_SETTING_KEY,
  ZEPHYR_WORKBENCH_BUILD_PRISTINE_SETTING_KEY,
  ZEPHYR_PROJECT_WEST_WORKSPACE_SETTING_KEY,
  ZEPHYR_PROJECT_BOARD_SETTING_KEY,
  ZEPHYR_PROJECT_SDK_SETTING_KEY,
  ZEPHYR_PROJECT_TOOLCHAIN_SETTING_KEY,
  ZEPHYR_PROJECT_IAR_SETTING_KEY,
  ZEPHYR_PROJECT_EXTRA_WEST_ARGS_SETTING_KEY,
  ZEPHYR_ENV_SETTING_PREFIX_KEY,
  ZEPHYR_BUILD_CONFIG_WEST_ARGS_SETTING_KEY,
  ZEPHYR_BUILD_CONFIG_SYSBUILD_SETTING_KEY,
  ZEPHYR_BUILD_CONFIG_DEFAULT_RUNNER_SETTING_KEY,
  ZINSTALLER_MINIMUM_VERSION,
} from '../../constants';

describe('constants', () => {
  it('exports expected string constants', () => {
    assert.equal(ZEPHYR_DIRNAME, 'zephyr');
    assert.equal(ZEPHYR_APP_FILENAME, 'zephyr.elf');

    assert.equal(ZEPHYR_WORKBENCH_SETTING_SECTION_KEY, 'zephyr-workbench');
    assert.equal(ZEPHYR_WORKBENCH_PATH_TO_ENV_SCRIPT_SETTING_KEY, 'pathToEnvScript');
    assert.equal(ZEPHYR_WORKBENCH_VENV_ACTIVATE_PATH_SETTING_KEY, 'venv.activatePath');
    assert.equal(ZEPHYR_WORKBENCH_VENV_PATH_SETTING_KEY, 'venv.path');
    assert.equal(ZEPHYR_WORKBENCH_LIST_SDKS_SETTING_KEY, 'listSDKs');
    assert.equal(ZEPHYR_WORKBENCH_LIST_IARS_SETTING_KEY, 'listIARs');
    assert.equal(ZEPHYR_WORKBENCH_OPENOCD_SEARCH_DIR_SETTING_KEY, 'openocd.searchDir');
    assert.equal(ZEPHYR_WORKBENCH_OPENOCD_EXECPATH_SETTING_KEY, 'openocd.execPath');
    assert.equal(ZEPHYR_WORKBENCH_BUILD_PRISTINE_SETTING_KEY, 'build.pristine');

    assert.equal(ZEPHYR_PROJECT_WEST_WORKSPACE_SETTING_KEY, 'westWorkspace');
    assert.equal(ZEPHYR_PROJECT_BOARD_SETTING_KEY, 'board');
    assert.equal(ZEPHYR_PROJECT_SDK_SETTING_KEY, 'sdk');
    assert.equal(ZEPHYR_PROJECT_TOOLCHAIN_SETTING_KEY, 'toolchain');
    assert.equal(ZEPHYR_PROJECT_IAR_SETTING_KEY, 'iar');
    assert.equal(ZEPHYR_PROJECT_EXTRA_WEST_ARGS_SETTING_KEY, 'build.west-args');

    assert.equal(ZEPHYR_ENV_SETTING_PREFIX_KEY, 'env');
    assert.equal(ZEPHYR_BUILD_CONFIG_WEST_ARGS_SETTING_KEY, 'west-args');
    assert.equal(ZEPHYR_BUILD_CONFIG_SYSBUILD_SETTING_KEY, 'sysbuild');
    assert.equal(ZEPHYR_BUILD_CONFIG_DEFAULT_RUNNER_SETTING_KEY, 'default-runner');

    assert.equal(typeof ZINSTALLER_MINIMUM_VERSION, 'string');
    assert.ok(ZINSTALLER_MINIMUM_VERSION.length > 0);
  });
});
