#--- use versionning, this is needed to manage env.yml, mainly for auto-detect ---
version: 1
other_content:
- tool: yq
  os:
    windows:
      source: https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_windows_amd64.exe
      sha256: 5EF80368CAFC466A66222956607D09F66EAF7B8FFF93EE9253D847CC5AE38F1A
    linux:
      source: https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64
      sha256: cfbbb9ba72c9402ef4ab9d8f843439693dfb380927921740e51706d90869c7e1
    darwin:
      source: https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_darwin_amd64
      sha256: fdc42b132ac460037f4f0f48caea82138772c651d91cfbb735210075ddfdbaed
- tool: wget
  os:
    windows:
      source: https://eternallybored.org/misc/wget/1.21.4/64/wget.exe
      sha256: 6136e66e41acd14c409c2d3eb10d48a32febaba04267303d0460ed3bee746cc5
- tool: 7z
  os:
    windows:
      source: https://www.7-zip.org/a/7z2405-x64.exe
      sha256: 12EF1C8127EC3465520E4CFD23605B708D81A5A2CF37BA124F018E5C094DE0D9
- tool: zstd
  os:
    windows:
      source: https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-v1.5.6-win64.zip
      sha256: 7B4EFF6719990E38ACA93A4844C2E86A1935090625C4611F7E89675E999C56CC
- tool: msys2_runtime
  os:
    windows:
      source: https://repo.msys2.org/msys/x86_64/msys2-runtime-3.5.3-4-x86_64.pkg.tar.zst
      sha256: 838fd8a0a1aca2e5e19eed3155dbb086cc79fa5e701728b58843f2f6b1b1ed1a
- tool: libyaml
  os:
    windows:
      source: https://repo.msys2.org/msys/x86_64/libyaml-0.2.5-2-x86_64.pkg.tar.zst
      sha256: 11509c6e3133b3fc63f99cc04e89a1cc5685aa746e96bd5f481e3424fbd4f6c1
debug_tools:
- tool: openocd-zephyr
  alias: openocd
  name: OpenOCD Zephyr
  version: 0.12.0
  website: https://github.com/zephyrproject-rtos/openocd
  type: debug_server
  group: Openocds
  install_dir: openocds/openocd-zephyr
  root: false
  os:
    windows:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/common/openocd-zephyr/win32/openocd-zephyr-0.12.0-win32-x86_64.7z
      sha256: d5cea76f71872620f6f3e390c7935dce84ff97d4a840677bbc868595f5a10cbf
    linux:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/common/openocd-zephyr/linux/openocd-zephyr-0.12.0-linux-x86_64.tar.xz
      sha256: 07fd7b4b7175cea09b413c240ddc42c681f9e4e6cd1e23b1a18f056aad7eb3a6
    darwin:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/common/openocd-zephyr/darwin/openocd-zephyr-0.12.0-darwin-arm64.tar.xz
      sha256: 3123f6d42454cbb2af03bbea48e5c4f93fe7c556119d64b4372f249e4ba14ee9
- tool: openocd-esp32
  alias: openocd
  name: OpenOCD ESP32
  version: 0.12.0
  website: https://github.com/espressif/openocd-esp32/releases
  type: debug_server
  group: Openocds
  install_dir: openocds/openocd-esp32
  root: false
  os:
    windows:
      source: https://github.com/espressif/openocd-esp32/releases/download/v0.12.0-esp32-20251215/openocd-esp32-win32-0.12.0-esp32-20251215.zip
      sha256: 032a3791c256c974bceced073dc8cf0e18c07a75f39592110cbe71fc8de914b2
    linux:
      source: https://github.com/espressif/openocd-esp32/releases/download/v0.12.0-esp32-20251215/openocd-esp32-linux-amd64-0.12.0-esp32-20251215.tar.gz
      sha256: 5e6ff40aeca23bdd203cde04d60bc808c0e6bff110eadcbce3d602618c880531
    darwin:
      source: https://github.com/espressif/openocd-esp32/releases/download/v0.12.0-esp32-20251215/openocd-esp32-macos-0.12.0-esp32-20251215.tar.gz
      sha256: 956dd02ccf35116d565be2b148e041bd47c135e551a1f5097eae756d7d4dd079
- tool: openocd-xpack
  alias: openocd
  name: OpenOCD xPack
  version: 0.12.0
  website: https://github.com/xpack-dev-tools/openocd-xpack/releases
  type: debug_server
  group: Openocds
  install_dir: openocds/openocd-xpack
  root: false
  os:
    windows:
      source: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-7/xpack-openocd-0.12.0-7-win32-x64.zip
      sha256: 6bfd3c97135aafef8affc9af1acf34fd0e2b9ca26044506f6abd7f95b7630052
    linux:
      source: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-7/xpack-openocd-0.12.0-7-linux-x64.tar.gz
      sha256: 94b3790983beaf8ed57e646c0620dd66d705fddae03d290823a6ed3b439468d6
    darwin:
      source: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-7/xpack-openocd-0.12.0-7-darwin-x64.tar.gz
      sha256: 668ad25350103a4357e11629ec833eae5982e973889ce25bad0c2963e37fa8bf
- tool: openocd-custom
  alias: openocd
  name: OpenOCD Custom 
  version: 0.12.0
  website: https://openocd.org/
  type: debug_server
  group: Openocds
  install_dir: openocds/openocd-custom
  root: false
  os:
    windows: false
    linux: false
    darwin: false
- tool: jlink
  name: J-Link Software
  version: 8.78
  website: https://www.segger.com/downloads/jlink/
  vendor: Segger
  type: debug_server
  group: Common
  root: false
  auto-detect:
    windows:
      - "C:/Program Files/SEGGER/JLink*"
      - "C:/Program Files (x86)/SEGGER/JLink*"
    linux:
      - "/opt/SEGGER/JLink*"
      - "/usr/local/SEGGER/JLink*"
    darwin:
      - "/Applications/SEGGER/JLink*"
      - "/Applications/JLink*"
- tool: stm32cubeprogrammer
  name: STM32CubeProgrammer
  version: 2.17.0 
  website: https://www.st.com/en/development-tools/stm32cubeprog.html
  vendor: ST
  type: flasher
  group: STM32
  root: false
# Auto-detect common installation paths, use wildcards as needed:
# "*" → multiple characters (e.g., any version number)
# "?" → exactly one character
  auto-detect:
    windows:
      - "C:/Program Files/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin"
      - "C:/Program Files (x86)/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin"
      - "C:/ST/STM32CubeCLT_*/STM32CubeProgrammer/bin"
    linux:
      - "/usr/local/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin"
      - "/opt/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin"
      - "/usr/bin/STM32_Programmer_CLI"
      - "/usr/local/bin/STM32_Programmer_CLI"
      - "${HOME}/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin"
    darwin:
      - "/Applications/STMicroelectronics/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOS/bin"
      - "/Applications/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOS/bin"
- tool: linkserver
  name: NXP LinkServer for Microcontrollers
  version: 24.9.75
  website: https://www.nxp.com/design/design-center/software/development-software/mcuxpresso-software-and-tools-/linkserver-for-microcontrollers:LINKERSERVER
  vendor: NXP
  type: debug_server
  group: NXP
  auto-detect:
    windows:
      - "C:/NXP/LinkServer_*"
    linux:
      - "/opt/NXP/LinkServer*"
      - "/usr/local/NXP/LinkServer*"
      - "/opt/linkserver*"
    darwin:
      - "/Applications/LinkServer*"
- tool: nrfjprog
  name: nRF Command Line Tools
  version: 10.24.2
  website: https://www.nordicsemi.com/Products/Development-tools/nRF-Command-Line-Tools/Download
  vendor: Nordic Semiconductor
  type: flasher
  group: Nordic
  root: false
  os:
    windows:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/nordic/nrfjprog/win32/nrf-command-line-tools-10.24.2-x64.exe
      sha256: f3bcd0d7209fbd758a5828a8e5b9afcebfd1281554ea0baaa0c60b8c9aa50ea9
    linux:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/nordic/nrfjprog/linux/nrf-command-line-tools-10.24.2_linux-amd64.tar.gz
      sha256: 9d65b0d80fccb567668fa41585c9261947b1740f52eba8d3a368cf6f8fd7b793
#    darwin:
#      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/nordic/nrfjprog/darwin/nrf-command-line-tools-10.24.2-darwin.dmg
#      sha256: c7f24bb4234e3e99e408a3f7cca568898a51779f2f337604c2e8d60466939c2e
- tool: nrfutil
  name: nRF Util
  version: 8.1.1
  website: https://www.nordicsemi.com/Products/Development-tools/nRF-Util
  vendor: Nordic Semiconductor
  type: flasher
  group: Nordic
  root: false
  os:
    windows:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/nordic/nrfutil/win32/8.1.1/nrfutil.exe
      sha256: SKIP
    linux:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/nordic/nrfutil/linux/8.1.1/nrfutil
      sha256: ccd67d0c6026ec472d091eb08d008c6b3a6302c84b79da3c3ee62cd30d0bff26
    darwin:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/runners/nordic/nrfutil/darwin/8.1.1/nrfutil
      sha256: 726c8e6e4cb5e0811f342620f88472351b1203f2af8e27b744e653f34a08deb4
- tool: simplicity_commander
  name: Silabs Simplicity Commander
  version: 1v20p5b1945
  website: https://www.silabs.com/software-and-tools/simplicity-studio/simplicity-commander
  vendor: Silicon Labs
  type: flasher
  group: Silabs
  root: false
  os:
    windows:
      source: https://www.silabs.com/documents/public/software/SimplicityCommander-Windows.zip
      sha256: SKIP
    linux:
      source: https://www.silabs.com/documents/public/software/SimplicityCommander-Linux.zip
      sha256: SKIP
    darwin:
      source: https://www.silabs.com/documents/public/software/SimplicityCommander-Mac.zip
      sha256: SKIP
  auto-detect:
    windows:
      - "C:/SiliconLabs/SimplicityCommander*"
    linux:
      - "/opt/SimplicityCommander*"
      - "/usr/local/SimplicityCommander*"
    darwin:
      - "/Applications/SimplicityCommander.app/Contents/MacOS"
- tool: pyocd
  name: pyOCD
  version: 0.36.0
  website: https://pyocd.io/
  type: debug_server
  group: Common
  no_edit: true
  os:
    windows: true
    linux: true
    darwin: true
- tool: cp210x
  name: USB to UART Bridge VCP CP210x Universal Drivers 
  version: 11.4.0 
  website: https://www.silabs.com/developer-tools/usb-to-uart-bridge-vcp-drivers
  vendor: Silicon Labs
  type: driver
  group: Silabs
  root: true
  no_edit: true
  os:
    windows:
      source: https://www.silabs.com/documents/public/software/CP210x_Universal_Windows_Driver.zip
      sha256: SKIP
    linux: false
    darwin: false
- tool: udev-rules
  name: Udev Rules for STLink, JLink and libUSB
  version: 1.0.0 
  website:
  vendor: No
  type: driver
  group: Common
  root: true
  no_edit: true
  os:
    linux:
      source: https://www.ac6-tools.com/downloads/zephyr-workbench/tools/linux/zw-udev-rules-1.0.0.tar.xz
      sha256: 0cd477139825438cef3e1f15ec01be801c9b9dfcf3085c43d7af284122f862b9
    windows: false
    darwin: false
packs:
- pack: stm32
  name: STM32
  tools: [openocd, stm32cubeprogrammer, jlink, udev-rules]
- pack: nxp
  name: NXP
  tools: [linkserver, jlink]
- pack: nordic
  name: Nordic
  tools: [jlink, nrfutil, nrfjprog]
- pack: silabs
  name: Silabs
  tools: [simplicity_commander, cp210x, jlink]
- pack: esp32
  name: ESP32
  tools: [cp210x]

aliases:
- alias: openocd
  name: OpenOCD
  default: openocd-zephyr 