// Generation and upkeep of clangd IntelliSense configuration for an application.
// Parallel to the cpptools (c_cpp_properties.json) path in ZephyrTaskProvider:
// a per-application .clangd file points clangd at the active build's
// compilation database, and a workbench-owned --query-driver argument lets
// clangd trust the Zephyr SDK / Arm GNU cross-compiler for system headers.
import * as fs from 'fs';
import * as fsPromise from 'fs/promises';
import * as path from 'path';
import * as ts from 'typescript';
import * as vscode from 'vscode';
import { CLANGD_EXTENSION_ID, isClangdInstalled } from './providerAvailability';

// First line of every generated .clangd file. A file that does not start with
// this marker is treated as user-authored and never overwritten or deleted.
const CLANGD_MANAGED_MARKER = '# Generated by Zephyr Workbench. Manual edits will be overwritten.';

const CPP_INTELLISENSE_ENGINE_KEY = 'C_Cpp.intelliSenseEngine';
const CPP_INTELLISENSE_ENGINE_DISABLED = 'disabled';

const QUERY_DRIVER_PREFIX = '--query-driver=';

type PathMode = 'relative' | 'absolute';

function toPosix(p: string): string {
  return p.split(path.sep).join('/');
}

export function getClangdConfigPath(workspaceFolder: vscode.WorkspaceFolder): string {
  return path.join(workspaceFolder.uri.fsPath, '.clangd');
}

function renderClangdConfig(workspaceFolder: vscode.WorkspaceFolder, compileCommandsDir: string, pathMode: PathMode): string {
  const dir = pathMode === 'absolute'
    ? toPosix(compileCommandsDir)
    : toPosix(path.relative(workspaceFolder.uri.fsPath, compileCommandsDir)) || '.';
  return [
    CLANGD_MANAGED_MARKER,
    'CompileFlags:',
    `  CompilationDatabase: ${dir}`,
    '',
  ].join('\n');
}

function isManagedClangdFile(contents: string): boolean {
  return contents.split(/\r?\n/, 1)[0]?.trim() === CLANGD_MANAGED_MARKER;
}

/**
 * Write (or refresh) the managed .clangd file so clangd reads the given
 * compilation-database directory. Leaves a user-authored .clangd untouched and
 * skips the write when the content is already up to date. Returns whether a
 * write happened.
 */
export async function updateClangdConfigFile(
  workspaceFolder: vscode.WorkspaceFolder,
  options: { compileCommandsDir: string; pathMode?: PathMode }
): Promise<boolean> {
  const clangdPath = getClangdConfigPath(workspaceFolder);
  const next = renderClangdConfig(workspaceFolder, options.compileCommandsDir, options.pathMode ?? 'relative');

  if (fs.existsSync(clangdPath)) {
    let current: string;
    try {
      current = await fsPromise.readFile(clangdPath, 'utf8');
    } catch {
      return false;
    }
    if (!isManagedClangdFile(current)) {
      // User-authored file: respect it, do not clobber.
      return false;
    }
    if (current === next) {
      return false;
    }
  }

  await fsPromise.mkdir(path.dirname(clangdPath), { recursive: true });
  await fsPromise.writeFile(clangdPath, next, 'utf8');
  return true;
}

/** Whether a workbench-managed (marker-bearing) .clangd file exists in the folder. */
export async function hasManagedClangdConfig(workspaceFolder: vscode.WorkspaceFolder): Promise<boolean> {
  const clangdPath = getClangdConfigPath(workspaceFolder);
  if (!fs.existsSync(clangdPath)) {
    return false;
  }
  try {
    return isManagedClangdFile(await fsPromise.readFile(clangdPath, 'utf8'));
  } catch {
    return false;
  }
}

/**
 * Delete the managed .clangd file. Strict no-op when the file is absent or was
 * authored by the user (marker missing).
 */
export async function removeClangdConfigFile(workspaceFolder: vscode.WorkspaceFolder): Promise<boolean> {
  const clangdPath = getClangdConfigPath(workspaceFolder);
  if (!fs.existsSync(clangdPath)) {
    return false;
  }
  try {
    const current = await fsPromise.readFile(clangdPath, 'utf8');
    if (!isManagedClangdFile(current)) {
      return false;
    }
    await fsPromise.rm(clangdPath);
    return true;
  } catch {
    return false;
  }
}

/** Glob that allows clangd to query the compiler in the given executable's directory. */
export function getQueryDriverGlobForCompiler(compilerPath: string): string | undefined {
  if (!compilerPath) {
    return undefined;
  }
  return `${toPosix(path.dirname(compilerPath))}/*`;
}

/**
 * Broad fallback glob for the archless-custom-board case where the exact
 * compiler path is not known until after the first build. Matches the
 * per-toolchain bin directories under an SDK root.
 */
export function getQueryDriverFallbackGlob(sdkRootPath: string): string | undefined {
  if (!sdkRootPath) {
    return undefined;
  }
  return `${toPosix(sdkRootPath)}/*/bin/*`;
}

function collectExistingQueryDriverGlobs(args: string[]): string[] {
  const globs: string[] = [];
  for (const arg of args) {
    if (typeof arg === 'string' && arg.startsWith(QUERY_DRIVER_PREFIX)) {
      const value = arg.slice(QUERY_DRIVER_PREFIX.length);
      for (const glob of value.split(',')) {
        const trimmed = glob.trim();
        if (trimmed) {
          globs.push(trimmed);
        }
      }
    }
  }
  return globs;
}

// Workbench-managed clangd behavior flags, appended once each. They are never
// applied over a value the user already set for the same flag.
// --header-insertion=never stops clangd auto-inserting #include lines on
// completion (noisy and often wrong in Zephyr/embedded code);
// --completion-style=detailed lists overloads separately rather than bundling.
const MANAGED_CLANGD_FLAGS = ['--header-insertion=never', '--completion-style=detailed'];

/** The identity of a clangd argument for de-duplication: the `--flag=` prefix, or the whole flag. */
function clangdArgKey(arg: string): string {
  const eq = arg.indexOf('=');
  return eq === -1 ? arg : arg.slice(0, eq + 1);
}

/**
 * Ensure the workbench-managed entries are present in `clangd.arguments`
 * (Workspace scope): the behavior flags above plus the given query-driver globs.
 * Additive and non-destructive: behavior flags are appended only when the user
 * has not set that flag; query-driver globs are merged into a single
 * --query-driver argument (union, sorted), never removing globs or reordering
 * other user arguments. All changes are written in one update. Returns whether
 * the setting changed.
 *
 * No-op when clangd is not installed: `clangd.arguments` is contributed by the
 * clangd extension, so writing it while absent would throw. Every sync trigger
 * re-ensures these, so installing clangd later converges.
 */
export async function ensureManagedClangdArguments(queryDriverGlobs: Array<string | undefined>): Promise<boolean> {
  if (!isClangdInstalled()) {
    return false;
  }

  const config = vscode.workspace.getConfiguration('clangd');
  let next = [...(config.inspect<string[]>('arguments')?.workspaceValue ?? [])];
  let changed = false;

  // Behavior flags: append each only when the user has not set that flag.
  const presentKeys = new Set(next.map(clangdArgKey));
  for (const flag of MANAGED_CLANGD_FLAGS) {
    if (!presentKeys.has(clangdArgKey(flag))) {
      next.push(flag);
      changed = true;
    }
  }

  // Query-driver globs: merge missing ones into a single --query-driver argument.
  const desiredGlobs = queryDriverGlobs.filter((g): g is string => !!g);
  if (desiredGlobs.length > 0) {
    const existingGlobs = new Set(collectExistingQueryDriverGlobs(next));
    const missing = desiredGlobs.filter(g => !existingGlobs.has(g));
    if (missing.length > 0) {
      const union = Array.from(new Set([...existingGlobs, ...desiredGlobs])).sort();
      const mergedArg = `${QUERY_DRIVER_PREFIX}${union.join(',')}`;
      const rebuilt: string[] = [];
      let replaced = false;
      for (const arg of next) {
        if (typeof arg === 'string' && arg.startsWith(QUERY_DRIVER_PREFIX)) {
          // Fold every existing query-driver into the first slot; drop the rest.
          if (!replaced) {
            rebuilt.push(mergedArg);
            replaced = true;
          }
        } else {
          rebuilt.push(arg);
        }
      }
      if (!replaced) {
        rebuilt.push(mergedArg);
      }
      next = rebuilt;
      changed = true;
    }
  }

  if (changed) {
    await config.update('arguments', next, vscode.ConfigurationTarget.Workspace);
  }
  return changed;
}

/**
 * Ask the clangd server to reload after a `clangd.arguments` change (arguments
 * are only read at startup). Best-effort: silent when clangd is missing or the
 * command is unavailable. Not needed for .clangd file edits, which clangd
 * re-reads automatically.
 */
export async function restartClangdServer(): Promise<void> {
  if (!isClangdInstalled()) {
    return;
  }
  try {
    await vscode.commands.executeCommand('clangd.restart');
  } catch {
    // clangd not active yet or command unavailable; the new arguments apply on next start.
  }
}

// --- cpptools suppression (folder scope) -------------------------------------
// Written by direct file edit rather than the configuration API: at creation
// time the app folder is not yet in the workspace, and when cpptools is absent
// the C_Cpp.* keys are unregistered and API writes would throw.

async function readFolderSettings(
  workspaceFolder: vscode.WorkspaceFolder
): Promise<{ settingsJsonPath: string; config: Record<string, unknown>; serialized?: string; writable: boolean }> {
  const settingsJsonPath = path.join(workspaceFolder.uri.fsPath, '.vscode', 'settings.json');
  if (!fs.existsSync(settingsJsonPath)) {
    return { settingsJsonPath, config: {}, writable: true };
  }
  try {
    const serialized = await fsPromise.readFile(settingsJsonPath, 'utf8');
    const parsed = ts.parseConfigFileTextToJson(settingsJsonPath, serialized);
    if (parsed.error || !parsed.config || typeof parsed.config !== 'object' || Array.isArray(parsed.config)) {
      return { settingsJsonPath, config: {}, serialized, writable: false };
    }
    return { settingsJsonPath, config: parsed.config as Record<string, unknown>, serialized, writable: true };
  } catch {
    return { settingsJsonPath, config: {}, writable: false };
  }
}

async function writeFolderSettings(settingsJsonPath: string, config: Record<string, unknown>, previousSerialized?: string): Promise<boolean> {
  const nextSerialized = JSON.stringify(config, null, 2);
  if (nextSerialized === previousSerialized) {
    return false;
  }
  await fsPromise.mkdir(path.dirname(settingsJsonPath), { recursive: true });
  await fsPromise.writeFile(settingsJsonPath, nextSerialized, 'utf8');
  return true;
}

/**
 * Disable the cpptools IntelliSense engine for this folder so it does not double
 * up with clangd. No-op when clangd is not installed: there is nothing to double
 * up with, and disabling cpptools then would leave the folder with no working
 * provider at all.
 */
export async function applyCppToolsSuppression(workspaceFolder: vscode.WorkspaceFolder): Promise<boolean> {
  if (!isClangdInstalled()) {
    return false;
  }
  const { settingsJsonPath, config, serialized, writable } = await readFolderSettings(workspaceFolder);
  if (!writable) {
    return false;
  }
  if (config[CPP_INTELLISENSE_ENGINE_KEY] === CPP_INTELLISENSE_ENGINE_DISABLED) {
    return false;
  }
  config[CPP_INTELLISENSE_ENGINE_KEY] = CPP_INTELLISENSE_ENGINE_DISABLED;
  return writeFolderSettings(settingsJsonPath, config, serialized);
}

/**
 * Undo the workbench's clangd configuration for a folder (delete the managed
 * .clangd and clear the cpptools suppression), but ONLY when a workbench-managed
 * .clangd is present. Since the suppression key is only ever written alongside a
 * managed .clangd, this is the reliable signal that the workbench owns the
 * suppression: a folder the workbench never configured for clangd (e.g. one
 * where the user hand-set C_Cpp.intelliSenseEngine themselves) is left
 * byte-for-byte untouched.
 */
export async function clearManagedClangdArtifacts(workspaceFolder: vscode.WorkspaceFolder): Promise<void> {
  if (!(await hasManagedClangdConfig(workspaceFolder))) {
    return;
  }
  await removeClangdConfigFile(workspaceFolder);
  await clearCppToolsSuppression(workspaceFolder);
}

/**
 * Remove the workbench's cpptools suppression. Strict no-op when the key is
 * absent (no file created, no write) or when its value is not the exact
 * 'disabled' the workbench writes (a user override is left intact).
 */
export async function clearCppToolsSuppression(workspaceFolder: vscode.WorkspaceFolder): Promise<boolean> {
  const settingsJsonPath = path.join(workspaceFolder.uri.fsPath, '.vscode', 'settings.json');
  if (!fs.existsSync(settingsJsonPath)) {
    return false;
  }
  const { config, serialized, writable } = await readFolderSettings(workspaceFolder);
  if (!writable) {
    return false;
  }
  if (config[CPP_INTELLISENSE_ENGINE_KEY] !== CPP_INTELLISENSE_ENGINE_DISABLED) {
    return false;
  }
  delete config[CPP_INTELLISENSE_ENGINE_KEY];
  return writeFolderSettings(settingsJsonPath, config, serialized);
}

export { CLANGD_EXTENSION_ID };
